import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const iconsDir = resolve(root, "icons");
await mkdir(resolve(root, "src"), { recursive: true });

const SOCIAL_NAMES = new Set([
  "bluesky",
  "facebook",
  "github",
  "instagram",
  "linkedin",
  "mastodon",
  "tiktok",
  "twitter",
  "x",
  "youtube",
]);

const files = (await readdir(iconsDir))
  .filter((file) => file.endsWith(".svg"))
  .sort((a, b) => a.localeCompare(b));

if (files.length === 0) throw new Error("No SVG icons found");

const icons = [];
for (const file of files) {
  const name = file.slice(0, -4);
  if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(name)) {
    throw new Error(`${file}: filenames must be lowercase kebab-case`);
  }
  if (SOCIAL_NAMES.has(name)) throw new Error(`${file}: social/brand icons are not allowed`);

  const svg = await readFile(resolve(iconsDir, file), "utf8");
  const open = svg.match(/<svg\b([^>]*)>/i);
  const inner = svg.match(/<svg\b[^>]*>([\s\S]*?)<\/svg>/i)?.[1]?.trim();
  if (!open || !inner) throw new Error(`${file}: expected one non-empty <svg> root`);
  const viewBox = open[1].match(/viewBox=["']([^"']+)["']/i)?.[1];
  if (viewBox !== "0 0 24 24") throw new Error(`${file}: expected viewBox=\"0 0 24 24\"`);
  if (/\b(?:stroke|fill)=["'](?:black|#000(?:000)?)["']/i.test(inner)) {
    throw new Error(`${file}: use currentColor instead of a hardcoded black color`);
  }
  icons.push({ name, file, body: inner.replace(/\r\n/g, "\n") });
}

const generatedHeader = "// Generated by scripts/build.mjs — do not edit.\n";
const tsEntries = icons
  .map(({ name, body }) => `  ${JSON.stringify(name)}: ${JSON.stringify(body)},`)
  .join("\n");
const names = icons.map(({ name }) => JSON.stringify(name)).join(" | ");
const ts = `${generatedHeader}
export const ICON_VIEWBOX = "0 0 24 24" as const;
export type IconName = ${names};

export const ICONS: Readonly<Record<IconName, string>> = {
${tsEntries}
};

export const isIconName = (name: string): name is IconName =>
  Object.prototype.hasOwnProperty.call(ICONS, name);

export const iconSvg = (name: string, className = "size-6"): string =>
  isIconName(name)
    ? \`<svg class="\${className}" viewBox="\${ICON_VIEWBOX}" fill="none" aria-hidden="true">\${ICONS[name]}</svg>\`
    : "";

export const iconRef = (name: string | undefined, prefix = "publr-icon"): string =>
  name && isIconName(name) ? \`#\${prefix}-\${name}\` : "";

export function mountIconSprite(
  doc: Document = document,
  prefix = "publr-icon",
): SVGSVGElement {
  const existing = doc.getElementById(\`\${prefix}-sprite\`);
  if (existing instanceof SVGSVGElement) return existing;
  const host = doc.createElement("div");
  host.innerHTML = \`<svg id="\${prefix}-sprite" style="display:none" aria-hidden="true">\${Object.entries(ICONS)
    .map(([name, body]) => \`<symbol id="\${prefix}-\${name}" viewBox="\${ICON_VIEWBOX}">\${body}</symbol>\`)
    .join("")}</svg>\`;
  const sprite = host.firstElementChild as SVGSVGElement;
  doc.body.appendChild(sprite);
  return sprite;
}
`;

const zigIdent = (name) => name.replaceAll("-", "_");
const zigEscape = (line) => `    \\\\${line}`;
const zigConstants = icons
  .map(({ name, body }) => {
    const lines = body.split("\n").map((line) => line.trim()).filter(Boolean);
    return `pub const ${zigIdent(name)}: []const u8 =\n${lines.map(zigEscape).join("\n")}\n;`;
  })
  .join("\n\n");
const zig = `${generatedHeader}
pub const view_box = "0 0 24 24";
pub const Name = enum { ${icons.map(({ name }) => zigIdent(name)).join(", ")} };

${zigConstants}

pub fn get(name: Name) []const u8 {
    const values = comptime blk: {
        const fields = @typeInfo(Name).@"enum".fields;
        var result: [fields.len][]const u8 = undefined;
        for (fields, 0..) |field, index| result[index] = @field(@This(), field.name);
        break :blk result;
    };
    return values[@intFromEnum(name)];
}
`;

const manifest = {
  schemaVersion: 1,
  viewBox: "0 0 24 24",
  icons: icons.map(({ name, file }) => ({ name, file })),
};

await writeFile(resolve(root, "src/index.ts"), ts);
await writeFile(resolve(root, "publr_icons.zig"), zig);
await writeFile(resolve(root, "manifest.json"), `${JSON.stringify(manifest, null, 2)}\n`);
console.log(`Generated TypeScript and Zig adapters for ${icons.length} UI icons.`);
